spring.application.name=SpringBootActuatorDemo
server.port=8080

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always