spring.application.name=MiniBankingSpringBoot
# ==============================
# MySQL Configuration
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# ==============================
# Redis Configuration
# ==============================

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Use Redis as cache
spring.cache.type=redis