server.port=8080

spring.application.name=gateway-service





#Spring Cloud Gateway Server WebMVC

#spring.cloud.gateway.server.webmvc.routes[0].id=account_route
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/account/**
#
#spring.cloud.gateway.server.webmvc.routes[1].id=transaction_route
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/transaction/**
